const images = {
  animals: [
    {
      id: 1,
      path: require("../assets/images/animals/bear_img.jpg"),
      title: "Bear",
      description: "Bear",
      author: "pch.vector on Freepik",
    },
    {
      id: 2,
      path: require("../assets/images/animals/elephant_img.jpg"),
      title: "Elephant",
      description: "Elephant",
      author: "pch.vector on Freepik",
    },
    {
      id: 3,
      path: require("../assets/images/animals/lion_img.jpg"),
      title: "Lion",
      description: "Lion",
      author: "pch.vector on Freepik",
    },
    {
      id: 4,
      path: require("../assets/images/animals/fox_img.jpg"),
      title: "Fox",
      description: "Fox",
      author: "pch.vector on Freepik",
    },
    {
      id: 5,
      path: require("../assets/images/animals/giraffe_img.jpg"),
      title: "Giraffe",
      description: "Giraffe",
      author: "pch.vector on Freepik",
    },
    {
      id: 6,
      path: require("../assets/images/animals/penguin_img.jpg"),
      title: "Penguin",
      description: "Penguin",
      author: "pch.vector on Freepik",
    },
    {
      id: 7,
      path: require("../assets/images/animals/bunny_img.jpg"),
      title: "Bunny",
      description: "Bunny",
      author: "pch.vector on Freepik",
    },
    {
      id: 8,
      path: require("../assets/images/animals/pig_img.jpg"),
      title: "Pig",
      description: "Pig",
      author: "pch.vector on Freepik",
    },
  ],
  characters: [
    {
      id: 9,
      path: require("../assets/images/characters/character1_img.jpg"),
      title: "Character 1",
      description: "Little girl, purple shirt",
      author: "gstudioimagen1 on Freepik",
    },
    {
      id: 10,
      path: require("../assets/images/characters/character2_img.jpg"),
      title: "Character 2",
      description: "Little boy, red shirt",
      author: "gstudioimagen1 on Freepik",
    },
    {
      id: 11,
      path: require("../assets/images/characters/character3_img.jpg"),
      title: "Character 3",
      description: "Little girl, blue shirt",
      author: "gstudioimagen1 on Freepik",
    },
    {
      id: 12,
      path: require("../assets/images/characters/character4_img.jpg"),
      title: "Character 4",
      description: "Little boy, yellow shirt",
      author: "gstudioimagen1 on Freepik",
    },
    {
      id: 13,
      path: require("../assets/images/characters/character5_img.jpg"),
      title: "Character 5",
      description: "Little girl, blue dress",
      author: "gstudioimagen1 on Freepik",
    },
    {
      id: 14,
      path: require("../assets/images/characters/character6_img.jpg"),
      title: "Character 6",
      description: "Little boy, green shirt",
      author: "gstudioimagen1 on Freepik",
    },
    {
      id: 15,
      path: require("../assets/images/characters/character7_img.jpg"),
      title: "Character 7",
      description: "Little girl, yellow shirt",
      author: "gstudioimagen1 on Freepik",
    },
    {
      id: 16,
      path: require("../assets/images/characters/character8_img.jpg"),
      title: "Character 8",
      description: "Little boy, white shirt",
      author: "gstudioimagen1 on Freepik",
    },

  ],
  celebrations: [
    {
      id: 18,
      path: require("../assets/images/celebrations/birthday_img.jpg"),
      title: "Birthday",
      description: "Birthday",
      author: "Freepik",
    },
    {
      id: 19,
      path: require("../assets/images/celebrations/easter_img.jpg"),
      title: "Easter",
      description: "Easter",
      author: "Freepik",
    },
    {
      id: 20,
      path: require("../assets/images/celebrations/mothers_day_img.jpg"),
      title: "Mother's Day",
      description: "Mother's Day",
      author: "Freepik",
    },
    {
      id: 21,
      path: require("../assets/images/celebrations/fathers_day_img.jpg"),
      title: "Father's day",
      description: "Father's day",
      author: "Freepik",
    },
    {
      id: 22,
      path: require("../assets/images/celebrations/fourth_july_img.jpg"),
      title: "4th of July",
      description: "4th of July",
      author: "Freepik",
    },
    {
      id: 23,
      path: require("../assets/images/celebrations/halloween_img.jpg"),
      title: "Halloween",
      description: "Halloween",
      author: "Freepik",
    },
    {
      id: 24,
      path: require("../assets/images/celebrations/thanksgiving_img.jpg"),
      title: "Thanksgiving",
      description: "Thanksgiving",
      author: "Freepik",
    },
    {
      id: 25,
      path: require("../assets/images/celebrations/christmas_img.jpg"),
      title: "Christmas",
      description: "Christmas",
      author: "Freepik",
    },
  ],
};

export default images;
