const images = [
  {
    id: 1,
    url: require("../assets/images/animals/bear_image.jpg"),
    title: "Bear",
    description: "Bear",
    author: "pch.vector on Freepik",
  },
  {
    id: 2,
    url: require("../assets/images/animals/elephant_image.jpg"),
    title: "Elephant",
    description: "Elephant",
    author: "pch.vector on Freepik",
  },
  {
    id: 3,
    url: require("../assets/images/animals/lion_image.jpg"),
    title: "Lion",
    description: "Lion",
    author: "pch.vector on Freepik",
  },
  {
    id: 4,
    url: require("../assets/images/animals/fox_image.jpg"),
    title: "Fox",
    description: "Fox",
    author: "pch.vector on Freepik",
  },
  {
    id: 5,
    url: require("../assets/images/animals/giraffe_image.jpg"),
    title: "Giraffe",
    description: "Giraffe",
    author: "pch.vector on Freepik",
  },
  {
    id: 6,
    url: require("../assets/images/animals/penguin_image.jpg"),
    title: "Penguin",
    description: "Penguin",
    author: "pch.vector on Freepik",
  }, 
  {
    id: 7,
    url: require("../assets/images/animals/bunny_image.jpg"),
    title: "Bunny",
    description: "Bunny",
    author: "pch.vector on Freepik",
  }, 
  {
    id: 8,
    url: require("../assets/images/animals/pig_image.jpg"),
    title: "Pig",
    description: "Pig",
    author: "pch.vector on Freepik",
  },
  {
    id: 9,
    url: require("../assets/images/characters/character1_img.jpg"),
    title: "Character 1",
    description: "Little girl curly hair, wear glasses",
    author: "Freepik",
  },
  {
    id: 10,
    url: require("../assets/images/characters/character2_img.jpg"),
    title: "Character 2",
    description: "Little girl curly hair, wear glasses",
    author: "Freepik",
  },
  {
    id: 11,
    url: require("../assets/images/characters/character3_img.jpg"),
    title: "Character 3",
    description: "Little girl has a puppy",
    author: "Freepik",
  },
  {
    id: 12,
    url: require("../assets/images/characters/character4_img.jpg"),
    title: "Character 4",
    description: "Little girl blond hair",
    author: "Freepik",
  },
  {
    id: 13,
    url: require("../assets/images/celebrations/birthday_img.jpg"),
    title: "Birthday",
    description: "Birthday",
    author: "Freepik",
  },
  {
    id: 14,
    url: require("../assets/images/celebrations/easter_img.jpg"),
    title: "Easter",
    description: "Easter",
    author: "Freepik",
  },
  {
    id: 15,
    url: require("../assets/images/celebrations/mothers_day_img.jpg"),
    title: "Mother's Day",
    description: "Mother's Day",
    author: "Freepik",
  },
  {
    id: 16,
    url: require("../assets/images/celebrations/fathers_day_img.jpg"),
    title: "Father's day",
    description: "Father's day",
    author: "Freepik",
  },
  {
    id: 17,
    url: require("../assets/images/celebrations/fourth_july_img.jpg"),
    title: "4th of July",
    description: "4th of July",
    author: "Freepik",
  },
  {
    id: 18,
    url: require("../assets/images/celebrations/halloween_img.jpg"),
    title: "Halloween",
    description: "Halloween",
    author: "Freepik",
  }, 
  {
    id: 19,
    url: require("../assets/images/celebrations/thanksgiving_img.jpg"),
    title: "Thanksgiving",
    description: "Thanksgiving",
    author: "Freepik",
  }, 
  {
    id: 20,
    url: require("../assets/images/celebrations/christmas_img.jpg"),
    title: "Christmas",
    description: "Christmas",
    author: "Freepik",
  },
];

export default images;
