const images = [
  {
    id: 1,
    url: require("../assets/images/bear_image.jpg"),
    title: "Bear",
    description: "Bear",
    author: "pch.vector on Freepik",
  },
  {
    id: 2,
    url: require("../assets/images/elephant_image.jpg"),
    title: "Elephant",
    description: "Elephant",
    author: "pch.vector on Freepik",
  },
  {
    id: 3,
    url: require("../assets/images/lion_image.jpg"),
    title: "Lion",
    description: "Lion",
    author: "pch.vector on Freepik",
  },
  {
    id: 4,
    url: require("../assets/images/fox_image.jpg"),
    title: "Fox",
    description: "Fox",
    author: "pch.vector on Freepik",
  },
  {
    id: 5,
    url: require("../assets/images/giraffe_image.jpg"),
    title: "Giraffe",
    description: "Giraffe",
    author: "pch.vector on Freepik",
  },
  {
    id: 6,
    url: require("../assets/images/penguin_image.jpg"),
    title: "Penguin",
    description: "Penguin",
    author: "pch.vector on Freepik",
  }, 
  {
    id: 7,
    url: require("../assets/images/bunny_image.jpg"),
    title: "Bunny",
    description: "Bunny",
    author: "pch.vector on Freepik",
  }, 
  {
    id: 8,
    url: require("../assets/images/pig_image.jpg"),
    title: "Pig",
    description: "Pig",
    author: "pch.vector on Freepik",
  },
  {
    id: 9,
    url: require("../assets/images/character1_img.jpg"),
    title: "Character 1",
    description: "Little girl curly hair, wear glasses",
    author: "pch.vector on Freepik",
  },
  {
    id: 10,
    url: require("../assets/images/character2_img.jpg"),
    title: "Character 2",
    description: "Little girl curly hair, wear glasses",
    author: "pch.vector on Freepik",
  },
  {
    id: 11,
    url: require("../assets/images/character3_img.jpg"),
    title: "Character 3",
    description: "Little girl has a puppy",
    author: "pch.vector on Freepik",
  },
  {
    id: 12,
    url: require("../assets/images/character4_img.jpg"),
    title: "Character 4",
    description: "Little girl blond hair",
    author: "pch.vector on Freepik",
  },
];

export default images;
